name: Frontschweine
main: de.minestar.frontschweine.core.FrontschweineCore
version: ${pom.version}
softdepend: [GreenMile]
depend: [MineStarLibrary]
commands:
  fs:
    description: Frontschweine-related commands
    usage: /fs <command>